
name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools git
        git clone https://github.com/kevinputnam/js_basic_game.git
        pip3 install --user -r requirements.txt
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        python3 build.py
    - name: Push the docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/reDocs
        publish_branch: latestHTML